### ISSUE TITLE
damping function does not work in vasp.6.2.0

### ISSUE THREAD

**Issue by kchokawa** [aradi/SCPC-Method#1]
I am now using the SCPC method implemented in vasp.6.2.0 to calculate the vacancy defect in the tutorial Diamond.
I' have confirmed that SCPC method is working, but damping function does not work even when I set the RXCUT (or RYCUT,RZCUT).
Even if I change the input RXCUT, the output does not change and shows "Mixing rxcut: -1.0000".

[INCAR.txt](https://github.com/aradi/SCPC-Method/files/6544912/INCAR.txt)
[SCPCOUT.txt](https://github.com/aradi/SCPC-Method/files/6544913/SCPCOUT.txt)

**Comment by isobestico** [comment]
Dear Kchokawa, 

     Sorry for that. We are preparing a new release but it is not yet ready
     with other small corrections and/or new features.  

     However, to fix this minor issue you can try to use the patch in copy

     to apply the minor correction

     (1) first make a copy of your current version in the src directory of VASP-6.2
      
           % cd src
           % cp scpc.F scpc.F.origina.rev6
     
     (2) get the fix patch from here

     (3) apply the patch

          %patch scpc.F  missing_damp_vasp62.txt

[missing_damp_vasp62.txt](https://github.com/aradi/SCPC-Method/files/6546473/missing_damp_vasp62.txt)

**Comment by kchokawa** [comment]
Thank you for your very quick response.
I have succeeded to use the scpc method with damping function.
