### ISSUE TITLE
Killed at SCPC Cycle 1

### ISSUE THREAD

**Issue by boyguyue** [aradi/SCPC-Method#11]
Dear developer:
I am trying the TiO2 example. 
However, the task will be killed directly in SCPC Cycle1 of SCPC step.
[test.zip](https://github.com/aradi/SCPC-Method/files/10719961/test.zip)
My input file and error file are in the attachment. 
How can I solve this problem?
Many Thanks!

Yue Gu

**Comment by mlorke** [comment]
Sorry to get into this older issue,
but I'm having the same issues on HLRN, 
might that be raleated to the DL_MG version Mauricio?
Do you know where to get the appropriate one?
my email at U Bremen is still valid, so I would love to get in contact...
