### ISSUE TITLE
Segmentation fault error while running tutorial task

### ISSUE THREAD

**Issue by Essea** [aradi/SCPC-Method#12]
Dear developers,

I use vasp-5.4.4 and SCPC patch-rev7.
I'm trying to complete NaCl-slab tutorial task. I am going through manual steps, completing all neccesarry NEUTRAL, CHARGED and other folders and copy all mandarory files to SCPC-1.
When running, unfortunately I get the least informative error: "forrtl: severe (174): SIGSEGV, segmentation fault occurred".
Seems that all input files are read correctly (see slurm-file attached).
Probably the problem is lying somewhere in vasp compilation (or two external libraries) and I have no idea how to trace it.

Please find attached SCPC-1 output files as well as 3 makefiles: for VASP, for dlmg-v3.1.0 and pspfft packages.
[error_problem.zip](https://github.com/aradi/SCPC-Method/files/11782526/error_problem.zip)

mpiifort compilator was used for all three cases.
Also I noticed in VCOROUT file that printed information is repeated many times. I may guess that parallelization process has some fault but I don't see any problems in VASP OUTCAR file.
Thank you in advance for any comments and suggestions.

Yours sincerely

**Comment by isobestico** [comment]
Hi, 

  Please send an email in Univ. Lorraine that I will send you a previous version of dlmg library. I've noticed that the new version of dlmg is not working properly with the SCPC release. It seems the authors changed some input parameters and it may cause this abnormal crashes.

**Comment by isobestico** [comment]
Hi, 

    I've just checked our closed issues and you are using the version DLMG (3.1.0_rc17) which is probably the source of the reported error. Please check the previous issue report here

https://github.com/aradi/SCPC-Method/issues/5

   Try to use the older versions of the DLMG external library: 3.0.0; or the 2.0.2 that I am providing with the rev7 SCPC patch.

**Comment by Essea** [comment]
> I've just checked our closed issues and you are using the version DLMG (3.1.0_rc17) which is probably the source of the reported error. Please check the previous issue report here.
> ```
> Try to use the older versions of the DLMG external library: 3.0.0; or the 2.0.2 that I am providing with the rev7 SCPC patch.

Thank you a lot! As for 3.0.0 version - it was hard to find this version for downloading, while 2.0.2 has some problems with mpiifort compilation in my case. So, I finally used DL_MG 4.1.0 version - and everything works.

A bit interesting that for SCPC-1 I got 1.88 eV instead of tutorial-proposed 1.84 eV. For SCPC-2 they are equivalent - 1.94 eV.

If possible would you mind helping me with few more advices on SCPC method? Or, please, refer to some source to be read.

1. From da Silva et al. paper I can see that "The reference system can either be the pristine system <...> or the neutral defect <...>. The latter is, in principle, the correct procedure, but the former seems to be more practical".

So, am I right that in general choice of SCPC-1 or SCPC-2 (pristine or neutral defect reference) depends on the particular case? While neutral defect has more physical sense it requires update of charge density - therefore more efforts to be needed?
E.g. in tutorial cases no significant difference is observed and both methods can be applied.

2. Am I right that one needs to be very careful while relaxing defected 2D slabs? So practically authors **do not recommend** to relax defected slab **without** correction and applying of SCPC just for the final geometry?

3. Currently I cannot find how to properly set INVCOR parameter? Should I set it empirically to avoid possible electronic nonconvergence? In NaCl manual it is set to 1.

4. The similar question is about dumping region (VCR(X,Y,Z)CUT). Should I test it by myself to obtain consistent correction results? In tutorial these flags are omitted at all.

5. Am I right that only STATIC (i.e. no ionic contribution) dielectric component of bulk structure must be used for VCDIEL flag? At least, tutorial-used 2.46 value seems to be only static component for NaCl bulk as far as I know.

Thank you again!

**Comment by isobestico** [comment]
Hello, 

  Please copy all these questions and send them to my email at Univ. Lorraine. I will be pleased to answer
them by email since it is not related to the original issue open here.
 
  My email can be found in the original work you have already cited.
