### ISSUE TITLE
Question about dielectric constant values when using the SCPC method.

### ISSUE THREAD

**Issue by jwguo59** [aradi/SCPC-Method#16]
Hello,

While calculating the dielectric constant of a TeO2 model I constructed, I found that the dielectric constant of NaCl given on the VASP official website (https://www.vasp.at/wiki/index.php/Ionic_contributions_to_the_frequency_dependent_dielectric_function_of_NaCl) consists of two parts: the ionic contribution and the electronic contribution. I checked the dielectric constant value given in the /work-data/POSCAR-INCAR-File on your GitHub site, which is VCDIEL = 2.44. This value is close to the electronic part of the dielectric constant of NaCl given on the VASP website. Should I use this value in my calculations, or could you please explain in detail the specific steps and methods you use to calculate the dielectric constant using the SCPC method? If possible, I would be very grateful. (Attached is a screenshot of the dielectric constant of NaCl from the VASP website.)
![1164px-NaCl-diel-ion](https://github.com/user-attachments/assets/79d3900e-c42f-4731-bc2e-fab843568efe)

**Comment by isobestico** [comment]
Hello, 

  You can use either the 'eps_inf' or 'eps_0' (hint: eps_0 = eps_inf + eps_ion), but for sure you are not going to 
use the eps_ion alone. Hence, the eps_inf is enough for your calculations. For example, using the example you 
posted: 

    or you use eps_inf = "2.54" 
    or you use eps_0 = "5.87"      (eps_inf + esp_ion = 2.54 + 3.23) 

  The procedure to obtain the dielectric constant is not associate to the SCPC method, so you can follow the instructions provided by VASP tutorials/materials
