### ISSUE TITLE
Question about the formation energy calculations

### ISSUE THREAD

**Issue by YongchenZhu** [aradi/SCPC-Method#17]
Dear Prof. I have used this method to calculate the formation of 3D materials. But, I found the energy of the perfect supercell (just VASP calculations) and the defect materials (the energy obtained by the scpc method) with one negative charge has a big difference, nearly 100 eV, so I want to know is this normal? and for 3D materials, did we need set tne daming parameters?  Thank you!

**Comment by isobestico** [comment]
Hello, 

    Could you please give more information about your issue? 
    Could you send me the POSCAR and INCAR of your systems?
    Precisely how did you get this 100eV? Please write down 
what you did to get this energy - the systems you used, and their energies.

**Comment by YongchenZhu** [comment]
The energy of the charged (-1) defect of my materials when I just used VASP is -502.69161 eV，but when I use SCPC method, the total energy  becomes -436.163 eV，so the difference is nearly 66 eV，it's really a bigger difference. By the way, the correction energy in the SCPCOUT is 0.6 eV.  I don't know how to use these energy to calculate the formation energy of this defect, what's the relationship between these energies.

**Comment by YongchenZhu** [comment]
You can see the details in the attached files
[test.zip](https://github.com/user-attachments/files/16740314/test.zip)

**Comment by isobestico** [comment]
Hi, 

    Sorry, with the information you are providing to me I cannot help at all. it would be nice to check the POSCAR files 
for the pristine and the defect system if it is possible. I am saying that because the SCPC can only be used with 
orthogonal cells and the material should be insulator or semi-conductor. Hence, it would be nice to check your 
POSCAR file.

**Comment by YongchenZhu** [comment]
Yes, I have used a preconverged WAVECAR and CHGCAR and set IN=1, but the same results I obtained. the lattice parameter I used is 11x11x12 A.

**Comment by isobestico** [comment]
Then, I don´t what's going on and without the POSCAR it will be impossible to have a clue about if, sorry.

**Comment by isobestico** [comment]
Hi, in case you cannot share your POSCAR here due to some research aspect you can send me in my UnivLorraine email, check the original paper and send me your POSCAR directly to me in my UnivLorraine email

**Comment by YongchenZhu** [comment]
Hi, I did a test use your examples, bulk-diamond, I found if I use PBE functional, the results are reasonable, but if I use HSE06, the results are not reasonable, and it appeared the same wrong results with my systems. I have attached the files. Please give me some help, thank you.
[bulk-diamond.zip](https://github.com/user-attachments/files/16740707/bulk-diamond.zip)

**Comment by isobestico** [comment]
Hi, 

    I got your file, and I deleted it from here because you sent some protected files. I will check your issue
using the defect in Vc(-2).

**Comment by isobestico** [comment]
Hello,

Regarding the hybrid functional, you should not use ALGO=Damped when use SCPC and initial WAVECAR from the uncorrected hse06 charged system. You can simple copy the WAVECAR from the fully uncorrected charged system into the scpc calculation and NOT use ALGO=D and TIME=XXX. I think this should fix the issue with the ALGO Damp and SCPC method. So

-- run your charged system without SCPC in HSE06 level and save the WAVECAR
-- start your scpc in the HSE06 with the HSE06 wavecar from uncorreted charged system and do NOT use ALGO=D and  TIME=XXX

**Comment by YongchenZhu** [comment]
Thank you. I have tested my system, It's fine now.
