### ISSUE TITLE
Confusion about the Energy correction in SCPCOUT file

### ISSUE THREAD

**Issue by jwguo59** [aradi/SCPC-Method#18]
Hello, I have encountered some confusion when I am trying to reproduce the formation energy of a carbon vacancy with two negative charges in diamond from your GitHub repository. After completing the calculations, I checked the final energies of each calculation and found that the energy difference between the charged defect correction with SCPC and without SCPC does not match the correction value given in the last cycle of the SCPCOUT file, although the two values are very close:
The energy difference between the calculations with SCPC and without SCPC is:
`Ecorr =Escpc-Echg=-535.1014285-(-537.1167095)=2.01528096 eV`
The correction value given in the last cycle of the SCPCOUT file
`Energy Correction :  1.9232 Ev`
Although the two values are very close. I would like to know the reason for this discrepancy.
 Additionally, I enabled the hybrid functional option (HSE) in VASP for all calculations and found that for HSE calculations, there is also a significant difference between these two values.Which follews:
`Ecorr =Escpc-Echg=-627.5006549-(-629.5188839)=2.018229 eV`
`Energy Correction :  1.9243 Ev`
And what's more, The formation energy of the carbon vacancy defect calculated using HSE increased to 15.14789711 eV, which is significantly different from the energy obtained using PBE, which is 12.61973298 eV. Is this result reasonable? (Attached are my VASP folders for the PBE and HSE calculations)

**Comment by isobestico** [comment]
Hi, 

    As the other user, I deleted your folder because you are exposing private files. 
    The Ecorr in SCPCOUT is only for convergence check it is the integration of the immediate product of delta_rho*Vcor without any potential alignment. I needed to remove this in past but I forgot and now I left this project and the science/academia field and this value is still present in the SCPCOUT. The energy correction should be calculated as you did by the difference between the fully converged SCPC energy and the uncorrected charged system. 
  Regarding the hybrid functional, you should not use ALGO=Damped when use SCPC and initial WAVECAR from the uncorrected hse06 charged system. You can simple copy the WAVECAR from the fully uncorrected charged system into the scpc calculation and NOT use ALGO=D and TIME=XXX. I think this should fix the issue with the ALGO Damp and SCPC method.

**Comment by jwguo59** [comment]
> Hi,
> 
> As the other user, I deleted your folder because you are exposing private files.
> 
> The Ecorr in SCPCOUT is only for convergence check it is the integration of the immediate product of delta_rho*Vcor without any potential alignment. I needed to remove this in past but I forgot and now I left this project and the science/academia field and this value is still present in the SCPCOUT. The energy correction should be calculated as you did by the difference between the fully converged SCPC energy and the uncorrected charged system.
> 
> Regarding the hybrid functional, you should not use ALGO=Damped when use SCPC and initial WAVECAR from the uncorrected hse06 charged system. You can simple copy the WAVECAR from the fully uncorrected charged system into the scpc calculation and NOT use ALGO=D and TIME=XXX. I think this should fix the issue with the ALGO Damp and SCPC method.
> 
> -- run your charged system without SCPC in HSE06 level and save the WAVECAR -- start your scpc in the HSE06 with the HSE06 wavecar from uncorreted charged system and do NOT use ALGO=D and TIME=XXX

Hello,Thank you very much for reply to me.
 I have another question about the dielectric constant: When calculating with VASP, the dielectric constant of the material provided is a tensor, but in the SCPC parameters, the DIEL parameter input is a single number. I saw in the manual you provided that this value should be the average of the tensor in three directions. 
![Snipaste_2024-08-28_15-06-51](https://github.com/user-attachments/assets/ca3e79dc-29be-48c5-98b5-a5f248ad0540)

The figure gives two averages. In actual calculations, should the arithmetic mean or the geometric mean be used? Additionally, for materials with very strong dielectric anisotropy, such as a dielectric constant of 3 in the xx direction, 3 in the yy direction, and 10 in the zz direction, is it reasonable to use this averaging method to obtain the result?

**Comment by isobestico** [comment]
Hi, 

The scpc cannot deal properly with anisotropic dielectric so I gave a suggestion to use such kind of average; from my side there is no best choice mean/geometric averages. The user need to figure out which one should be good to the problem. Sorry, I don´t have any good answer for you in selecting the best choice for the dielectric average - I personally use the simplest ( mean value of the all e_ii component 1/3(exx+eyy+ezz)).
