### ISSUE TITLE
Energy Convergence Issue

### ISSUE THREAD

**Issue by jwguo59** [aradi/SCPC-Method#19]
Hello! When I use the SCPC version compiled with vasp.6.4.3 to optimize the Sn199S200 supercell, the energy suddenly drops significantly when the Self-consistent Potential Correction is ON. Subsequently, the energy fluctuations in the self-consistent calculations remain large and do not converge. This issue occasionally occurs when optimizing other supercell systems as well. Do you have any solutions? Below are my INCAR, POSCAR, and log file screenshots.

INCAR：
# Initial Guess
  ISTART = 1 ;
  ICHARG = 1 ;

  LVHAR = T ;

  NPAR = 4 ;
  NELECT = 3988.0 ;

# Functional Definition
  GGA = PE ;

  LREAL = Auto ;

# Ionic Relax.
  IBRION = -1 ;
  ISIF   =  0 ;
  NSW    =  0 ;

#SCPC ;
 SCPC {
    USE   = T    ; turning on the SCPC method
    IN    = 6    ; starting on the first cycles
    QTOT  = -2.00 ; formal defect charge
    #ZLOW  = 0.22 ; lower interface boundary
    #ZHIG  = 0.53 ; upper interface boundary
    DIEL  = 33.25 ; macroscopic dielectric
    #BROAD = 0.40 ; broadening for the interface
    #PRTX  = T    ; printing the averages on the X direction
    RXCUT = 0.15  ; damping region on X direction for the model charge
    RYCUT = 0.15  ;
    RZCUT = 0.15
 }
  NELM = 300 ;
  EDIFF  = 1.0e-6 ;
  EDIFFG = -0.01 ;
  PREC   = Accurate ;
  ISMEAR = 0 ;
  SIGMA  = 0.03 ;

PISCAR：
Generated by VASPKIT code
   1.00000000000000
    22.8412113189999992    0.0000000000000000    0.0000000000000000
     0.0000026837000000   20.1540832519999995    0.0000000000000000
     0.0000117370000000    0.0000000000000000   22.0358562468999999
   Sn   S
   199   200
Direct
  0.0605669422723167  0.0499627822355393  0.0239632272125974
  0.0605710343400716  0.0499543527999791  0.2245967439238186
  0.0608417993592383  0.0499682283288863  0.4243982425335844
  0.0610659233932438  0.0499708605252565  0.6245686095068521
  0.0609650832623387  0.0499651471770903  0.8241056391577857
  0.0606568287347358  0.2500484277805697  0.0242383000512518
  0.0604332282759614  0.2501563423282178  0.2244071535950383
  0.0607583928623328  0.2504723827889350  0.4248617588146431
  0.0611757879714503  0.2505176740078596  0.6244971711750864
  0.0610634177924041  0.2501931538582056  0.8239086128337334
  0.0607778994551182  0.4500852575649361  0.0242430924641610
..........
![image](https://github.com/user-attachments/assets/f71804c5-037b-40f9-bc7f-056341bdf135)

**Comment by isobestico** [comment]
https://github.com/aradi/SCPC-Method/tree/main/VASP

2.1 Only single point calculation. The SCPC, by the moment, cannot be used for ions/cell optimization. You can turn on the SCPC method but there won't have any effect to the forces.
