### ISSUE TITLE
VASP Compilation

### ISSUE THREAD

**Issue by mamachra** [aradi/SCPC-Method#2]
Hello, 

while trying to compile VASP.6.2.0 using the -DSCPC tag, the following error is generated: 

if [ ! -d build/std ] ; then mkdir build/std  ; fi;
cp src/makefile src/.objects src/makedeps.awk makefile.include build/std ;
make -C build/std VERSION=std cleandependencies -j1
make[1]: Entering directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std'
rm -f .depend
make[1]: Leaving directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std'
make -C build/std VERSION=std all
make[1]: Entering directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std'
rsync -ru ../../src/lib .
cp makefile.include lib
make -C lib -j1
make[2]: Entering directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std/lib'
make libdmy.a
make[3]: Entering directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std/lib'
make[3]: `libdmy.a' is up to date.
make[3]: Leaving directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std/lib'
make[2]: Leaving directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std/lib'
rsync -ru ../../src/parser .
cp makefile.include parser
make -C parser -j1
make[2]: Entering directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std/parser'
make libparser.a
make[3]: Entering directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std/parser'
make[3]: `libparser.a' is up to date.
make[3]: Leaving directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std/parser'
make[2]: Leaving directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std/parser'
rsync -u ../../src/*.F ../../src/*.inc .
rm -f vasp ; make vasp ; cp vasp ../../bin/vasp_std
make[2]: Entering directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std'
mpiifort -mkl=sequential -o vasp c2f_interface.o nccl2for.o simd.o base.o profiling.o string.o tutor.o version.o vhdf5_base.o incar_reader.o reader_base.o openmp.o openacc_struct.o mpi.o mpi_shmem.o mathtools.o hamil_struct.o radial_struct.o pseudo_struct.o mgrid_struct.o wave_struct.o nl_struct.o mkpoints_struct.o poscar_struct.o afqmc_struct.o phonon_struct.o fock_glb.o chi_glb.o smart_allocate.o xml.o extpot_glb.o constant.o vdwforcefield_glb.o jacobi.o main_mpi.o openacc.o scala.o asa.o lattice.o poscar.o ini.o mgrid.o setex_struct.o xclib.o vdw_nl.o xclib_grad.o setex.o radial.o pseudo.o gridq.o ebs.o symlib.o mkpoints.o wave.o wave_mpi.o wave_high.o bext.o spinsym.o symmetry.o lattlib.o random.o nonl.o nonlr.o nonl_high.o dfast.o choleski2.o mix.o hamil.o xcgrad.o xcspin.o potex1.o potex2.o constrmag.o cl_shift.o relativistic.o LDApU.o paw_base.o metagga.o egrad.o pawsym.o pawfock.o pawlhf.o diis.o rhfatm.o hyperfine.o fock_ace.o paw.o mkpoints_full.o charge.o Lebedev-Laikov.o stockholder.o dipol.o solvation.o scpc.o pot.o tet.o dos.o elf.o hamil_rot.o chain.o dyna.o fileio.o vhdf5.o sphpro.o us.o core_rel.o aedens.o wavpre.o wavpre_noio.o broyden.o dynbr.o reader.o writer.o xml_writer.o brent.o stufak.o opergrid.o stepver.o chgloc.o fast_aug.o fock_multipole.o fock.o fock_dbl.o fock_frc.o mkpoints_change.o subrot_cluster.o sym_grad.o mymath.o npt_dynamics.o subdftd3.o subdftd4.o internals.o dynconstr.o dimer_heyden.o dvvtrajectory.o vdwforcefield.o nmr.o pead.o k-proj.o subrot.o subrot_scf.o paircorrection.o rpa_force.o ml_interface.o force.o pwlhf.o gw_model.o optreal.o steep.o rmm-diis.o davidson.o david_inner.o root_find.o lcao_bare.o locproj.o electron_common.o electron.o rot.o electron_all.o shm.o pardens.o optics.o constr_cell_relax.o stm.o finite_diff.o elpol.o hamil_lr.o rmm-diis_lr.o subrot_lr.o lr_helper.o hamil_lrf.o elinear_response.o ilinear_response.o linear_optics.o setlocalpp.o wannier.o electron_OEP.o electron_lhf.o twoelectron4o.o gauss_quad.o m_unirnk.o minimax_ini.o minimax_dependence.o minimax_functions1D.o minimax_functions2D.o minimax_struct.o minimax_varpro.o minimax.o mlwf.o ratpol.o pade_fit.o screened_2e.o wave_cacher.o crpa.o chi_base.o wpot.o local_field.o ump2.o ump2kpar.o fcidump.o ump2no.o bse_te.o bse.o time_propagation.o acfdt.o afqmc.o rpax.o chi.o acfdt_GG.o dmft.o GG_base.o greens_orbital.o lt_mp2.o rnd_orb_mp2.o greens_real_space.o chi_GG.o chi_super.o sydmat.o rmm-diis_mlr.o linear_response_NMR.o wannier_interpol.o wave_interpolate.o linear_response.o auger.o dmatrix.o phonon.o wannier_mats.o elphon.o core_con_mat.o embed.o extpot.o fftmpiw.o fftmpi_map.o fft3dlib.o fftw3d.o   main.o  -Llib -ldmy -Lparser -lparser /opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_scalapack_lp64.a -lmkl_blacs_intelmpi_lp64 -lstdc++
scpc.o: In function `scpc_mp_scpc_mgsolver_':
scpc.f90:(.text+0x14dc4): undefined reference to `dl_mg_mp_dl_mg_init_'
scpc.f90:(.text+0x15bae): undefined reference to `dl_mg_mp_dl_mg_solver_poisson_'
scpc.f90:(.text+0x15bba): undefined reference to `dl_mg_mp_dl_mg_free_'
scpc.o: In function `scpc_mp_scpc_solve_isopot_':
scpc.f90:(.text+0x1a65e): undefined reference to `variablearraygroup_base_mp_initialize_var_3d_g_'
scpc.f90:(.text+0x1aa7b): undefined reference to `poissonequations_fft__form_mp_create_pe_'
scpc.f90:(.text+0x1aad7): undefined reference to `poissonequations_fft__form_mp_solve_pe_'
scpc.f90:(.text+0x1aae1): undefined reference to `poissonequations_fft__form_mp_destroy_pe_'
scpc.f90:(.text+0x1b04b): undefined reference to `variablearraygroup_base_mp_finalize_var_3d_g_'
make[2]: *** [vasp] Error 1
make[2]: Leaving directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std'
cp: cannot stat ‘vasp’: No such file or directory
make[1]: *** [all] Error 1
make[1]: Leaving directory `/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/build/std'
make: *** [std] Error 2

The makefile.include used here is: 

# Precompiler options
CPP_OPTIONS= -DHOST=\"LinuxIFC\"\
             -DMPI -DMPI_BLOCK=8000 -Duse_collective \
             -DscaLAPACK \
             -DCACHE_SIZE=4000 \
             -Davoidalloc \
             -Dvasp6 \
             -Duse_bse_te \
             -Dtbdyn \
             -Dfock_dblbuf \
             -DSCPC

CPP        = fpp -f_com=no -free -w0  $*$(FUFFIX) $*$(SUFFIX) $(CPP_OPTIONS)

FC         = mpiifort
FCL        = mpiifort -mkl=sequential

FREE       = -free -names lowercase

FFLAGS     = -assume byterecl -w -xHOST
OFLAG      = -O2
OFLAG_IN   = $(OFLAG)
DEBUG      = -O0

MKL_PATH   = $(MKLROOT)/lib/intel64
BLAS       =
LAPACK     =
BLACS      = -lmkl_blacs_intelmpi_lp64
SCALAPACK  = $(MKL_PATH)/libmkl_scalapack_lp64.a $(BLACS)

OBJECTS    = fftmpiw.o fftmpi_map.o fft3dlib.o fftw3d.o

#INCS       =-I$(MKLROOT)/include/fftw

INCS       =-I$(MKLROOT)/include/fftw -I/home/mamachra/bin/VASP.6.2.0/vasp.6.2.0/pspfft-1.0/include /home/mamachra/bin/VASP.6.2.0/dlmgteam-dl_mg_code_public-e8cb96912d3a/lib/libdlmg.a
LLIBS      = $(SCALAPACK) $(LAPACK) $(BLAS)

OBJECTS_O1 += fftw3d.o fftmpi.o fftmpiw.o
OBJECTS_O2 += fft3dlib.o

# For what used to be vasp.5.lib
CPP_LIB    = $(CPP)
FC_LIB     = $(FC)
CC_LIB     = icc
CFLAGS_LIB = -O
FFLAGS_LIB = -O1
FREE_LIB   = $(FREE)

OBJECTS_LIB= linpack_double.o getshmem.o

# For the parser library
CXX_PARS   = icpc
LLIBS      += -lstdc++

# Normally no need to change this
SRCDIR     = ../../src
BINDIR     = ../../bin

#================================================
# GPU Stuff

CPP_GPU    = -DCUDA_GPU -DRPROMU_CPROJ_OVERLAP -DUSE_PINNED_MEMORY -DCUFFT_MIN=28 -UscaLAPACK -Ufock_dblbuf

OBJECTS_GPU= fftmpiw.o fftmpi_map.o fft3dlib.o fftw3d_gpu.o fftmpiw_gpu.o

CC         = icc
CXX        = icpc
CFLAGS     = -fPIC -DADD_ -Wall -qopenmp -DMAGMA_WITH_MKL -DMAGMA_SETAFFINITY -DGPUSHMEM=300 -DHAVE_CUBLAS

# Minimal requirement is CUDA >= 10.X. For "sm_80" you need CUDA >= 11.X.
CUDA_ROOT  ?= /usr/local/cuda/
NVCC       := $(CUDA_ROOT)/bin/nvcc -ccbin=icc -allow-unsupported-compiler
CUDA_LIB   := -L$(CUDA_ROOT)/lib64 -lnvToolsExt -lcudart -lcuda -lcufft -lcublas

GENCODE_ARCH    := -gencode=arch=compute_60,code=\"sm_60,compute_60\" \
                   -gencode=arch=compute_70,code=\"sm_70,compute_70\" \
                   -gencode=arch=compute_80,code=\"sm_80,compute_80\"

## For all legacy Intel MPI versions (before 2021)
#MPI_INC    = $(I_MPI_ROOT)/intel64/include/

# Or when you are using the Intel oneAPI compiler suite
MPI_INC    = $(I_MPI_ROOT)/include/

The operating system and environment are: 
intel/2018.1.163
mkl/2018.1.163
fftw/3.3.8
openmpi_ib/3.1.4
intelmpi/2018.1.163
gnu/7.2.0

Thank you for your help.

**Comment by isobestico** [comment]
Dear user, 

      Please verify in our installation notes a suggestion for 
      adapting your makefile to compile with SCPC

      After the original appearance of LLIBS and INC 

   INCS =-I$(MKLROOT)/include/fftw 
   LLIBS = $(SCALAPACK) $(LAPACK) $(BLAS)

      you should add and edit to your local installation (for sure)

   DLMGROOT   = <some_place_you_installed>/dl_mg_2.1.4
   PSPFFTROOT = <some_place_you_installed>/pspfft-1.0
   INCS  +=-I$(DLMGROOT)/lib
   INCS  +=-I$(PSPFFTROOT)/include
   LLIBS +=-Wl,--start-group $(DLMGROOT)/lib/libdlmg.a -Wl,--end-group
   LLIBS +=-Wl,--start-group $(PSPFFTROOT)/lib/libpspfft.a -Wl,--end-group
