### ISSUE TITLE
The energy correction issue of SCPC

### ISSUE THREAD

**Issue by zcxjq** [aradi/SCPC-Method#20]
Dear developer, I have encountered the following issue. In VASP 6.4.3, I used the neutral state of the charged defect as a reference and generated CHGCAR and LOCPOT files as REFCHG and REFPOT for correction. However, there is a significant energy difference before and after the SCPC correction. What could be the problem?Here are the screenshots of the relevant files.
INCAR:
SYSTEM=NiGa2O4   
ISTART=1
ICHARG=1
PREC=Accurate
ALGO=All
NELECT=4308
NSW=0
IBRION=-1       #-1:the atom don't move
ISIF=2
ENCUT=500
EDIFF=1E-05      #convergence  standard
LVHAR=.True. 
NELMIN = 5       #the least step number of electronic scf
NELM   = 500     #the most step number of electronic scf
ISMEAR=0
SIGMA=0.01
NCORE=8          #camputation speed
NPAR=8
ISPIN=2
SCPC {
  USE=T
  IN=1
  QTOT=-1
  DIEL=9.2
}

The CHGCAR and WAECAR files are obtained from the converged charged defect calculation before the correction.

POSCAR：
<img width="477" alt="3d8eee19681ec6fb1c3ed1697dafcc0" src="https://github.com/user-attachments/assets/d1d96c73-cb58-4da4-b42d-b57050ca6a50" />

KPOINTS:
K-Spacing Value to Generate K-Mesh: 0.000
0
Gamma
   1   1   1
0.0  0.0  0.0

POTCAR: the number of valence electrons.
Ga13    Ni10  O6

Screenshot of OSZICAR before the SCPC correction.
![image](https://github.com/user-attachments/assets/f7b918c0-8c76-4ac9-911c-e6f4b30751ee)
Screenshot of OSZICAR after the SCPC correction.
![image](https://github.com/user-attachments/assets/105c84c7-8556-4712-8723-181ceeb1d1bd)

 I have already tested the diamond system you provided, and the energy difference before and after the correction does not exceed 2 eV.I would like to know why there is such a large difference before and after the correction.  looking forward to your response and I would greatly appreciate it.

**Comment by isobestico** [comment]
Dear user, 

     Could you prepared and upload here a zip file with your INCAR and POSCAR for the neutral and charged system? Unfortunately with this info I cannot have a clue about what is going on. I will do my best to reproduce your issue but I am not working anymore in this project and I am out of academia which leave with modest computational resource (my own personal laptop) to help you. In other words maybe it will took a while to answer properly.

**Comment by 12za** [comment]
[all.zip](https://github.com/user-attachments/files/18222042/all.zip)
Attached are my relevant files, including three folders: negatively charged without correction, negatively charged with correction, and neutral system. Thank you once again, and sincerely wish you good health and success in your work.

**Comment by isobestico** [comment]
Hi tks, sorry I forgot to ask, please add the pristine system. I need to see the real position of your defect in the POSCAR. I need to check the defect, and it is only possible comparing with the system without any defect (pristine)

**Comment by 12za** [comment]
Dear Developer,
I am studying defects in tetrahedrally coordinated Ga. Since I need to calculate the formation energy as a function of the Fermi level, I need to compute the system energies for charge states of -1, -2, and -3. Attached is the POSCAR file for the perfect system.
[POSCAR.txt](https://github.com/user-attachments/files/18222100/POSCAR.txt)

**Comment by isobestico** [comment]
Ok, I will check it. From a first glance I didn´t see anything wrong. But as I explained I have few computational resources I will do my best to reproduce the issue and come back to you asp.

**Comment by 12za** [comment]
Thank you again for your help.Wish you success in your work and good health.

**Comment by isobestico** [comment]
Sorry, I won´t be able to run your unit cell. The size is OK and you should be using something of this length but I cannot afford this calculation in my laptop. You probably used a smaller unit cell to generate this one. Could you send me the pristine smaller unit cell for your system? I checked the exp cif file and there is fractional occupation, I wouldn't like to deal with it now to test the issue. So it would be easier to have your pristine smaller unit cell for debugging the reported issue.

**Comment by zcxjq** [comment]
[112 atoms system.zip](https://github.com/user-attachments/files/18223906/112.atoms.system.zip)
Dear Developer, this is the file I used for calculations with a 112-atom system. Initially, I utilized these files for the calculations, but after discovering the issue, I switched to using the unit cell size I first sent to you for the calculations. However, it turned out to be futile.

**Comment by isobestico** [comment]
Please check for me if there is a band gap in your pristine system (without any defect) when your are using PBE. Actually, I built a pristine NiGa2O4 small unit cell and it is a conductor material - I mean with PBE I cannot see band gap. SCPC can only be used in insulator or semi-conductor materials. Maybe I did some mistake, I will continue tomorrow.

**Comment by zcxjq** [comment]
Well,thank you for your response. In my tests: using PBE, the bandgap of the original system is only 0.6 eV (Up), and the magnetic ground state is ferromagnetic. When conducting the tests, I also considered the bandgap issue, so I tested the DFT+U method as well, where the effective U value for each Ni was set to 3. Under this condition, I obtained a bandgap of approximately 1.4 eV. However, when using the DFT+U method, there is a difference of about 70 eV between the energy before and after the SCPC correction.
pristine  pbe+u：
![image](https://github.com/user-attachments/assets/b5cfaef7-901a-4057-befc-8e617d328420)
pbe：
![image](https://github.com/user-attachments/assets/0621bd4f-9732-4849-9359-22afca7f5963)

**Comment by isobestico** [comment]
Hello, 

I did some tests with your small unit cell as well as with one new unit cell for the NiGa2O4 material. I tested the VGa(-1) in all the unit cell and I smoothly converged the SCPC. Considering the unit cell that I built I also used GGA+U and again I converged SCPC. I am copying here the inputs. Could you please rerun all the calculations using your compilation? Also, I built a 222 unit cell based on my unit cell, could you also try to run using this large unit cell? Please use my INCAR files and rebuild the POTCAR based on the IONS list of the POSCAR.

Inside the directory scpc there is a bash scrip COPY to copy the files needed by the SCPC. The WAVECAR and CHGCAR files come from the converged charged system without SCPC and the LOCPOT and CHGCAR come from the neutral defect calculations. 

[toShare.zip](https://github.com/user-attachments/files/18247363/toShare.zip)

**Comment by zcxjq** [comment]
Thank you for your feedback. I will proceed with testing next and will provide feedback once I have the results. Thank you!

**Comment by zcxjq** [comment]
Hello, Thanks for your help .I found that using the INCAR file you provided, my own system can also converge perfectly, and the results are quite consistent with those obtained without the charged system correction. Thank you! However, I have the following questions:

In your INCAR file, the cutoff energy was not specified, and NEDOS is set to 2001. Additionally, NPAR=2 is specified (does this parallelization parameter NPAR have a significant impact?).
For the k-points, you used Gamma. Is SCPC applicable to settings with multiple k-points?
Isn't the SCPC method incompatible with meta-GGA calculations? I tested a system with 504 atoms and a single Gamma point, and the energy difference before and after the correction was nearly 300 eV.

**Comment by isobestico** [comment]
Hello, 

You can now start adapting the INCAR to your needs and increase the precision (PREC=Acc, ENCUT=xxx, LASPH=XXX etc). I think previously you did some mistake in copy the right files WAVECAR and CHGCAR from the converged charged system without SCPC. Also you don´t need to use ISTART anymore, VASP will use WAVECAR and CHGCAR if they are present to build the initial guess for a calculation.

Anyways, the keyword NPAR/NCORE affect the parallelization not the SCPC method, this should not be the source of your previous issue. You can use more KPOINTS but since the SCPC methods needs a large unit cell (>~15A length each direction) and max symmetric cell the GAMMA approximation is enough for this condition. You probably won´t need more than GAMMA trick to use SCPC method - and it is faster. You can use SCPC with meta-GGA, but sometimes you can find some issues when use ALGO=DAMP. My recommendation is to follow VASP instruction to converge meta-GGA with the neutral and charged without SCPC method to build the essential files for SCPC. Then, to run the charged system with SCPC method with meta-GGA you may avoid the ALGO=Damped, you can use the normal ALGO because you are going to start the calculation with WAVECAR and CHGCAR from a meta-GGA converged charged system without SCPC.

I think the previous issue here was about the meta-GGA

**Comment by zcxjq** [comment]
Hello~, I noticed that in the "user" folder you sent me, you used a single k-point. I also obtained good results using a single k-point, but when I changed it to a 4×4×3 k-point grid, an energy difference of several tens of eV appeared before and after the correction.

**Comment by isobestico** [comment]
Hi, 

Thank you for reporting, maybe we have some issue with multiple Kpoints. I have never noticed it because I was always using large unit cells and for those systems gamma trick is enough. It's noted. As I explained to you I am out of this project and the academia I cannot afford improvements in the method anymore, sorry.

**Comment by zcxjq** [comment]
Thank you for your patient response, I have learned a lot. I truly appreciate your contributions to the academic community. Wishing you good health and success in your work~

**Comment by zcxjq** [comment]
Alright, after my tests, I found that the issue was not related to the k-points but instead to the ALGO setting. When I changed ALGO=All to the default Normal, everything ran perfectly. However, if ALGO=All is used, there is still a significant energy difference before and after the correction. I hope this will help future readers avoid this issue~

**Comment by isobestico** [comment]
Hi, thank you. I have already updated the issue warning

https://github.com/aradi/SCPC-Method/blob/main/VASP/warning-issues-bugs/README.md
