### ISSUE TITLE
Is the SCPC method implemented in VASP.6.3.0 along with the patches?

### ISSUE THREAD

**Issue by Shibu778** [aradi/SCPC-Method#7]
If the SCPC method is implemented in vasp.6.3.0, then how to compile vasp to use scpc method?

**Comment by isobestico** [comment]
You will probably find SCPC in vasp-6.3.0 (I'm not sure) but you also should apply a corrective patch for SCPC-rev7 at Vasp6. Please send us an email to get the correction patch. 

https://github.com/aradi/SCPC-Method/tree/main/VASP/patches/revision_7

the installation procedure was already written here in github page

https://github.com/aradi/SCPC-Method/blob/main/VASP/INSTALLATION.md

**Comment by Shibu778** [comment]
Thank you for providing me with the patch. I found the patch rev7 and the scpc.F90 in src of vasp.6.3.0 is exactly the same except some changes in the citation of papers. So, the rev7 is already included in vasp.6.3.0, right?

**Comment by isobestico** [comment]
I am pretty sure that I've never personally sent the rev7 to VASP team; maybe some of the other authors had updated the release inside VASP without contacting me (or minimum let me know about that). Good to know, thanks for the information.

**Comment by aradi** [comment]
I wasn't aware of that either...
