### ISSUE TITLE
SCPC Quantum espresso version

### ISSUE THREAD

**Issue by RjGuo** [aradi/SCPC-Method#9]
Does SCPC method have Quantum espresso version?

**Comment by isobestico** [comment]
Officially no! However, yes, I have the first version of SCPC in QE. Historically the project started with the development of a module for QE, however, we have migrated the development to VASP. Depending on your demand and collaboration I could revive the QE code, but I don't have so much enough time and interest for this at the moment. Drop me an email and we could discuss it if you wanna.
